def f2(a):
    c = 10
    print(a + x + c)



x = 4
f2(3)
print(x)
print(c) #da erro pois a variavel c foi criada dentro da função f2 e ela so existe dentro desta

     